// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import mermaid from 'astro-mermaid';

// Generated by nexis:wiki --target starlight (scripts/bootstrap-starlight.mjs).
export default defineConfig({
  integrations: [
    // must come before starlight() — astro-mermaid hooks the markdown pipeline
    // Starlight otherwise owns, so it needs first refusal on ```mermaid fences.
    mermaid({
      autoTheme: true,
    }),
    starlight({
      title: '__SITE_TITLE__',
      description: '__SITE_DESCRIPTION__',
    }),
  ],
});
