// Sidebar navigation for the nexis wiki.
//
// Regenerated by /nexis:wiki on every build/sync from the note taxonomy, so the
// navigation order and the section group labels match the wiki's own structure
// instead of Starlight's file-tree autogeneration (which alphabetizes pages and
// shows raw lower-case folder slugs as group labels). Do not hand-edit — your
// changes are overwritten on the next sync.
//
// Once populated it is an array of explicit `{ label, slug }` entries (and
// `{ label, items }` groups) — never `autogenerate`, which Starlight v0.39+
// rejects for labelled groups and which would re-alphabetize the nav anyway.
//
// `undefined` means "let Starlight autogenerate from the file tree" — the
// pre-first-build default, before any pages exist to order.
export const sidebar = undefined;
